#
# SPDX-License-Identifier: Apache-2.0
#
name: Test Network Ledger 🥑
run-name: ${{ github.actor }} is running the Test Network Ledger tests 🥑

on:
    workflow_dispatch:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    basic:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                chaincode-language:
                    - go
                    - javascript
                chaincode-name:
                    - ledger
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up the test network runtime
              uses: ./.github/actions/greenchain-network-setup

            - name: Run Test
              working-directory: greenchain-network
              run: ../ci/scripts/run-greenchain-network-ledger.sh
              env:
                  CHAINCODE_NAME: ${{ matrix.chaincode-name }}
                  CHAINCODE_LANGUAGE: ${{ matrix.chaincode-language }}
