# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &Bank4
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Bank4MSP

        # ID to load the MSP definition as
        ID: Bank4MSP

        MSPDir: ../organizations/peerOrganizations/bank4.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Bank4MSP.admin', 'Bank4MSP.peer', 'Bank4MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Bank4MSP.admin', 'Bank4MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Bank4MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Bank4MSP.peer')"
